schema {
	query: Query
}
type Query {
	getTokenPairRate(tickers: [TickerInput]): [Ticker]
}
scalar Date
input TickerInput {
	pair: String!
	datetime: Date!
}
type Ticker {
	pair: String!
	datetime: Date!
	rate: Float
}
