schema {
	query: Query
}
type Query {
	getTokenPairRate(tickers: [TickerInput]): [TickerOutput]
	# getAddressTransactions(addresses: [AddressesInput]): [Transactions]
}
input TickerInput {
	exchange: String
	pair: String!
	datetime: Date!
}
type TickerOutput {
	exchange: String!
	pair: String!
	datetime: [Date!]!
	id: [String]
	rate: Float
}
# input AddressesInput {
# 	address: String!
# }
scalar Date
